name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
      max-parallel: 3
      # fail-fast: true
    runs-on: matrix.os

    steps:
      - name: Checkout
      - uses: actions/checkout@v2

      - name: Configure toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --verbose

      # - name: Build
      #   run: cargo build --manifest-path=findrc/Cargo.toml --release --verbose
      # - name: Run tests
      #   run: cargo test --manifest-path=findrc/Cargo.toml --verbose
